### ISSUE TITLE
Custom font definition  not respected

### ISSUE THREAD

**Issue by cdaecke** [mittwald/typo3-web2pdf#116]
Thanks a lot for sharing your extension!

I am trying to use some custom font in generated PDF files.
This is my CSS definition:

``` CSS
.teaser {
    font-family: DINWeb;
    font-size: 15px;
    line-height: 20px;
    margin-top: 0;
    font-weight: normal;
}
```
The font file is located in `EXT:web2pdf/Resources/Public/Fonts/`. The file is named `DINWeb.ttf`.

Unfortunately the font is not used for `<div class="teaser">Test</div>`.

Am I missing something?

TYPO3: v10.4.8
ext:web2pdf: v 2.0.1
